# Generated by Django 4.0.1 on 2022-01-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='conta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contas.contas'),
        ),
    ]
