# Generated by Django 4.0.1 on 2022-01-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.CharField(max_length=50)),
                ('tipoConta', models.CharField(choices=[('CA', 'carteira'), ('CC', 'conta corrente'), ('PO', 'poupança')], max_length=2)),
                ('instituicaoFinanceira', models.CharField(max_length=255)),
            ],
        ),
    ]
