# Generated by Django 4.0.1 on 2022-01-15 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('tipoConta', models.CharField(choices=[('', '--------'), ('CA', 'Carteira'), ('CC', 'Conta Corrente'), ('PO', 'Poupança')], max_length=2, verbose_name='Tipo de Conta')),
                ('instituicaoFinanceira', models.CharField(max_length=255, verbose_name='Instituição Financeira')),
            ],
        ),
    ]
