# Generated by Django 4.0 on 2022-01-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('tipoConta', models.CharField(choices=[('CA', 'Carteira'), ('CC', 'Conta Corrente'), ('PO', 'Poupança')], max_length=2)),
                ('instituicaoFinanceira', models.CharField(max_length=255)),
            ],
        ),
    ]
