# Generated by Django 4.0.1 on 2022-01-04 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('dataRecebimento', models.DateField()),
                ('dataRecebimentoEsperado', models.DateField()),
                ('descricao', models.CharField(max_length=500, verbose_name='descrição')),
                ('tipoDespesa', models.CharField(choices=[('AL', 'alimentação'), ('ED', 'educação'), ('LA', 'lazer'), ('MO', 'moradia'), ('RO', 'roupa'), ('SA', 'saúde'), ('TR', 'transporte'), ('OU', 'outros')], max_length=2)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contas')),
            ],
        ),
    ]
